[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Function calling"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autopep8>=2.3.2",
    "numpy>=2.2.6",
    "pydantic>=2.13.3",
    "torch>=2.12.1",
    "transformers>=5.12.1",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=1.20.2",
]

[tool.ruff]
line-length = 80

[tool.ruff.format]
indent-style = "space"
indent-width = 2

[tool.ruff.lint]
select = ["D"] # pydocstyle

[tool.ruff.lint.pydocstyle]
convention = "google"
